export const metadata = {
	title: "About Page",
	description: "Generated by create next app",
};

export default function AboutLayout({ children }) {
	return (
		<>
			{children}
			<hr />
			<ul>
				<li>Footer 1</li>
				<li>Footer 1</li>

				<li>Footer 1</li>
			</ul>
		</>
	);
}
